version: '3.0'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ttfu
      - POSTGRES_PASSWORD=ttfu
      - POSTGRES_DB=ttfu